"""
Django settings for libraryProject project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t04p6if)2ng%(w-vayqbjo5y_7pnj#nf&$&h2(848syk66+e1+'

# SECURITY NOTE: set DEBUG=False in production for safety
DEBUG = False

# Update ALLOWED_HOSTS for your deployment; localhost and 127.0.0.1
# are included for local testing when DEBUG=False. Replace or extend
# this list for your real production hostnames.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf.apps.BookshelfConfig',
    'relationship_app.apps.RelationshipAppConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'libraryProject.middleware.ContentSecurityPolicyMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'libraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'libraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTH_USER_MODEL = 'bookshelf.CustomUser' 

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Security-related settings ---
# Enable browser XSS filter
SECURE_BROWSER_XSS_FILTER = True
# Prevent the browser from guessing the content type
SECURE_CONTENT_TYPE_NOSNIFF = True
# Restrict site from being framed
X_FRAME_OPTIONS = 'DENY'

# Ensure cookies are only sent over HTTPS in production
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Optional: set HSTS (uncomment and tune for production over HTTPS)
# Redirect all HTTP requests to HTTPS in production
# When True, Django will redirect all HTTP requests to HTTPS using a
# 301 redirect. Only enable this when your site is served over HTTPS.
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS)
# Instruct browsers to only access the site over HTTPS for the given time
# (seconds). 31536000 = 1 year and is commonly used when you're ready
# to enforce HTTPS permanently. Use a smaller value while testing.
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# If your site is behind a proxy/load balancer (e.g. nginx, AWS ELB)
# which terminates TLS and forwards traffic to Django via HTTP, set the
# following so Django knows the original request scheme. Ensure your
# proxy sets the `X-Forwarded-Proto` header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Note: Content-Security-Policy is set by the custom middleware

# ---------------------------------------------------------------------------
# Notes / Cautions
# - These settings are intended for production environments served over HTTPS.
# - During local development you may want to keep `DEBUG=True` and
#   `SECURE_SSL_REDIRECT=False` or conditionally set these using environment
#   variables to avoid redirect loops.
# - Enabling HSTS with a large `SECURE_HSTS_SECONDS` and `PRELOAD=True`
#   should only be done after you are sure all subdomains support HTTPS.
# ---------------------------------------------------------------------------

