# Generated by Django 5.2.8 on 2025-12-14 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='notifications',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['recipient', '-timestamp'], name='notificatio_recipie_aaca5e_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['recipient', 'read'], name='notificatio_recipie_9f897c_idx'),
        ),
    ]
