# Generated by Django 4.2.11 on 2025-12-14 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notifications_options_notifications_read_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_b8fa2a_idx',
            old_name='notificatio_recipie_aaca5e_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_6e3964_idx',
            old_name='notificatio_recipie_9f897c_idx',
        ),
    ]
